services:
  database:
    image: mysql:8.0.41
    volumes:
      - "./.mysql_data:/var/lib/mysql" 
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: --default-authentication-plugin=mysql_native_password


  nest-service:
    image: node:current-alpine3.21
    env_file:
      - ./.env
    command: "npm run start:dev"
    ports:
      - 3000:3000
    volumes: 
      - ./:/app
    working_dir: /app
    restart: always
    depends_on:
      - database

